name: Build Apple libraries and XCFrameworks

on:
  workflow_dispatch:

jobs:
  build:
    name: Build all the apple dependencies
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import code-signing keys
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
  
      - name: Build
        run: |
          ./make-apple.sh

      - name: Archive build artifacts
        run: |
          mkdir -p artifacts
          mv *.zip artifacts/

      - name: Upload ZIP files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apple-libraries
          path: artifacts/*.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: apple-libraries
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Apple Libraries Release
          allowUpdates: true
          draft: false
          prerelease: false
          artifacts: "artifacts/*.zip"
          replacesArtifacts: true
